package info.richardjones.mnemonics.loader;

public class HardCodedMnemonicMapLoader implements MnemonicMapLoader {

    @Override
    public void load(MnemonicMap map) {
//        map.add(new MatchingMnemonic("1jf1k", new MatchingMnemonicDetail("100% juice for 100% kids", "Juicy Juice","Slogan")));
//        map.add(new MatchingMnemonic("5v", new MatchingMnemonicDetail("57 varieties", "H.J. Heinz","Slogan")));
//        map.add(new MatchingMnemonic("9p", new MatchingMnemonicDetail("9944% pure", "Ivory Soap","Slogan")));
//        map.add(new MatchingMnemonic("Aabbnab", new MatchingMnemonicDetail("Always a bridesmaid, but never a bride", "Listerine","Slogan")));
//        map.add(new MatchingMnemonic("AAbtllmt", new MatchingMnemonicDetail("And All because the lady loves milk tray", "Cadbury’s Milk Tray","Slogan")));
        map.add(new MatchingMnemonic("Aaiaw", new MatchingMnemonicDetail("Ask about it at work", "Aflac","Slogan")));
        map.add(new MatchingMnemonic("AAsc", new MatchingMnemonicDetail("And America spells cheeseK-R-A-F-T", "Kraft","Slogan")));
        map.add(new MatchingMnemonic("AB", new MatchingMnemonicDetail("Ah! Bisto", "Bisto","Slogan")));
        map.add(new MatchingMnemonic("AB", new MatchingMnemonicDetail("Ah, Bisto!", "Bisto","Slogan")));
//        map.add(new MatchingMnemonic("AbbRbc", new MatchingMnemonicDetail("American by birth Rebel by choice", "Harley Davidson","Slogan")));
//        map.add(new MatchingMnemonic("Abbrbc", new MatchingMnemonicDetail("American by birth, rebel by choice", "Harley Davidson","Slogan")));
//        map.add(new MatchingMnemonic("Acawtawa", new MatchingMnemonicDetail("A can a week, that’s all we ask", "California Almond Growers","Slogan")));
//        map.add(new MatchingMnemonic("Adif", new MatchingMnemonicDetail("A diamond is forever", "De Beers","Slogan")));
//        map.add(new MatchingMnemonic("Agtdtd", new MatchingMnemonicDetail("Away go troubles down the drain", "Roto-Rooter","Slogan")));
//        map.add(new MatchingMnemonic("Aitpwthhm", new MatchingMnemonicDetail("Ace is the place with the helpful hardware man", "Ace Hardware","Slogan")));
//        map.add(new MatchingMnemonic("Alddy", new MatchingMnemonicDetail("A little dab’ll do ya", "Brylcreem","Slogan")));
//        map.add(new MatchingMnemonic("AlpA", new MatchingMnemonicDetail("Always low prices Always", "Wal-Mart","Slogan")));
//        map.add(new MatchingMnemonic("AMadhywrap", new MatchingMnemonicDetail("A Mars a day helps you work, rest and play", "Mars","Slogan")));
//        map.add(new MatchingMnemonic("Amfd", new MatchingMnemonicDetail("America’s most famous dessert", "Jell-O","Slogan")));
//        map.add(new MatchingMnemonic("Annas", new MatchingMnemonicDetail("A newspaper, not a snoozepaper", "The Mail on Sunday","Slogan")));
//        map.add(new MatchingMnemonic("Asml", new MatchingMnemonicDetail("A silly millimeter longer", "Chesterfield Cigarettes","Slogan")));
//        map.add(new MatchingMnemonic("Athoti", new MatchingMnemonicDetail("At the heart of the image", "Nikon","Slogan")));
//        map.add(new MatchingMnemonic("Atiap", new MatchingMnemonicDetail("Always there in a pinch", "Skoal","Slogan")));
//        map.add(new MatchingMnemonic("Atmwoo", new MatchingMnemonicDetail("Ask the man who owns one", "Packard","Slogan")));
//        map.add(new MatchingMnemonic("Atntftp", new MatchingMnemonicDetail("All the news that’s fit to print", "The New York Times","Slogan")));
//        map.add(new MatchingMnemonic("Avpoyw", new MatchingMnemonicDetail("A vital part of your world", "Tyco","Slogan")));
//        map.add(new MatchingMnemonic("AyacF&Nc", new MatchingMnemonicDetail("Are you a cadbury’s Fruit & Nut caase?", "Cadbury’s Fruit & Nut","Slogan")));
//        map.add(new MatchingMnemonic("AygyuDDywed", new MatchingMnemonicDetail("Aren’t you glad you use Dial? Don’t you wish everybody did?", "Dial Soap","Slogan")));
//        map.add(new MatchingMnemonic("B", new MatchingMnemonicDetail("Believe", "Yahoo! Personals","Slogan")));
//        map.add(new MatchingMnemonic("Baob", new MatchingMnemonicDetail("Babies are our business", "Gerber","Slogan")));
//        map.add(new MatchingMnemonic("Batycb", new MatchingMnemonicDetail("Be all that you can be", "U.S. Army","Slogan")));
//        map.add(new MatchingMnemonic("BbA", new MatchingMnemonicDetail("Better by Adobe", "Adobe","Slogan")));
//        map.add(new MatchingMnemonic("Bcejo", new MatchingMnemonicDetail("Betcha can’t eat just one", "Lay’s","Slogan")));
//        map.add(new MatchingMnemonic("BCH", new MatchingMnemonicDetail("Because Change Happens", "Zurich","Slogan")));
//        map.add(new MatchingMnemonic("Bftra", new MatchingMnemonicDetail("Built for the road ahead", "Ford","Slogan")));
//        map.add(new MatchingMnemonic("BIwfd", new MatchingMnemonicDetail("Beef It’s what’s for dinner", "National Cattlemen’s Beef Association","Slogan")));
//        map.add(new MatchingMnemonic("BIwi", new MatchingMnemonicDetail("Because I’m worth it", "L’Oréal","Slogan")));
//        map.add(new MatchingMnemonic("Blamlo", new MatchingMnemonicDetail("Between love and madness lies obsession", "Calvin Klein","Slogan")));
//        map.add(new MatchingMnemonic("Bltc", new MatchingMnemonicDetail("Better living through chemistry", "DuPont","Slogan")));
//        map.add(new MatchingMnemonic("BmH", new MatchingMnemonicDetail("Beanz means Heinz", "Heinz","Slogan")));
//        map.add(new MatchingMnemonic("Boc", new MatchingMnemonicDetail("Breakfast of champions", "Wheaties","Slogan")));
//        map.add(new MatchingMnemonic("Booto", new MatchingMnemonicDetail("Break out of the ordinary", "Nestles Butterfinger","Slogan")));
//        map.add(new MatchingMnemonic("BotBFabotb", new MatchingMnemonicDetail("Bring out the Best Foods and bring out the best", "Best Foods (Hellmann’s Mayonnaise)","Slogan")));
//        map.add(new MatchingMnemonic("Bs", new MatchingMnemonicDetail("Better snacking", "Sunkist","Slogan")));
//        map.add(new MatchingMnemonic("Bsmiroyt", new MatchingMnemonicDetail("Because so much is riding on your tires", "Michelin","Slogan")));
//        map.add(new MatchingMnemonic("Bstr", new MatchingMnemonicDetail("Better sound through research", "BOSE","Slogan")));
//        map.add(new MatchingMnemonic("Bt", new MatchingMnemonicDetail("Break through", "Cadillac","Slogan")));
//        map.add(new MatchingMnemonic("Btpoc", new MatchingMnemonicDetail("Behold the power of cheese", "American Dairy Association","Slogan")));
//        map.add(new MatchingMnemonic("Bww", new MatchingMnemonicDetail("Bayer works wonders", "Bayer Aspirin","Slogan")));
//        map.add(new MatchingMnemonic("Caib", new MatchingMnemonicDetail("Coffee at its best", "Nescafe Neighbour’s envy, owner’s pride","Slogan")));
//        map.add(new MatchingMnemonic("CaYitPg", new MatchingMnemonicDetail("Come alive! You’re in the Pepsi generation", "Pepsi","Slogan")));
//        map.add(new MatchingMnemonic("CBftGfy", new MatchingMnemonicDetail("Competition Bad for them Great for you", "DHL","Slogan")));
//        map.add(new MatchingMnemonic("Ce", new MatchingMnemonicDetail("Challenge everything", "EA ","Slogan")));
//        map.add(new MatchingMnemonic("Ce", new MatchingMnemonicDetail("Changes everything", "OneTouch","Slogan")));
//        map.add(new MatchingMnemonic("Cf", new MatchingMnemonicDetail("Choose freedom", "Toshiba","Slogan")));
//        map.add(new MatchingMnemonic("CfPM", new MatchingMnemonicDetail("Call for Philip Morris", "Philip Morris","Slogan")));
//        map.add(new MatchingMnemonic("Cii", new MatchingMnemonicDetail("Coke is it!", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("ClFlF", new MatchingMnemonicDetail("Cats like Felix, like Felix", "Felix","Slogan")));
//        map.add(new MatchingMnemonic("Cos", new MatchingMnemonicDetail("Catch our smile", "Pacific Southwest Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Cp", new MatchingMnemonicDetail("Connecting people", "Nokia","Slogan")));
//        map.add(new MatchingMnemonic("Cryb", new MatchingMnemonicDetail("Coca-Cola refreshes you best", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("Cshftg", new MatchingMnemonicDetail("Children’s shoes have far to go", "Smart","Slogan")));
//        map.add(new MatchingMnemonic("Ct", new MatchingMnemonicDetail("Capitalist tool", "Forbes","Slogan")));
//        map.add(new MatchingMnemonic("Cte", new MatchingMnemonicDetail("Cover the earth", "Sherwin Williams","Slogan")));
//        map.add(new MatchingMnemonic("CTfool", new MatchingMnemonicDetail("Cotton The fabric of our lives", "Cotton Incorporated","Slogan")));
//        map.add(new MatchingMnemonic("Ctma", new MatchingMnemonicDetail("Calgon, take me away", "Calgon Toiletries","Slogan")));
//        map.add(new MatchingMnemonic("CtMC", new MatchingMnemonicDetail("Come to Marlboro Country", "Marlboro","Slogan")));
//        map.add(new MatchingMnemonic("Ctmoyl", new MatchingMnemonicDetail("Celebrate the moments of your life", "General Foods","Slogan")));
//        map.add(new MatchingMnemonic("Cvttc", new MatchingMnemonicDetail("Creating value through true convergence", "Lucent Technologies","Slogan")));
//        map.add(new MatchingMnemonic("CwktC", new MatchingMnemonicDetail("Cooks who know trust Crisco", "Crisco Vegetable Shortening","Slogan")));
//        map.add(new MatchingMnemonic("Cyhmn", new MatchingMnemonicDetail("Can you hear me now?Good!", "Verizon Wireless","Slogan")));
//        map.add(new MatchingMnemonic("DB", new MatchingMnemonicDetail("Dream Bigger", "Superdream","Slogan")));
//        map.add(new MatchingMnemonic("DbE", new MatchingMnemonicDetail("Don’t be Evil", "Google","Slogan")));
//        map.add(new MatchingMnemonic("DbvafH", new MatchingMnemonicDetail("Don’t be vague, ask for Haig", "Haig Scotch Whiskey","Slogan")));
//        map.add(new MatchingMnemonic("DdiDi", new MatchingMnemonicDetail("Don’t dream it Drive it", "Jaguar","Slogan")));
//        map.add(new MatchingMnemonic("DgmGG", new MatchingMnemonicDetail("Don’t get mad Get GLAD", "GLAD","Slogan")));
//        map.add(new MatchingMnemonic("DjbiTCi", new MatchingMnemonicDetail("Don’t just book it Thomas Cook it", "Thomas Cook","Slogan")));
//        map.add(new MatchingMnemonic("DjtTr", new MatchingMnemonicDetail("Don’t just travel Travel right", "Expedia.com","Slogan")));
//        map.add(new MatchingMnemonic("Dlhwi", new MatchingMnemonicDetail("Don’t leave home without it", "American Express","Slogan")));
//        map.add(new MatchingMnemonic("Dm", new MatchingMnemonicDetail("Do more", "American Express","Slogan")));
//        map.add(new MatchingMnemonic("Dsods", new MatchingMnemonicDetail("Does she or doesn’t she?", "Clairol","Slogan")));
//        map.add(new MatchingMnemonic("DssM", new MatchingMnemonicDetail("Did somebody say McDonald’s?", "McDonald’s","Slogan")));
//        map.add(new MatchingMnemonic("DtD", new MatchingMnemonicDetail("Do the Dew", "Mountain Dew","Slogan")));
//        map.add(new MatchingMnemonic("Dw", new MatchingMnemonicDetail("Drivers wanted", "Volkswagen","Slogan")));
//        map.add(new MatchingMnemonic("DyddA", new MatchingMnemonicDetail("Doesn’t your dog deserve Alpo?", "Alpo Dog Food","Slogan")));
//        map.add(new MatchingMnemonic("DyMytt", new MatchingMnemonicDetail("Did you Maclean you teeth today", "Macleans","Slogan")));
//        map.add(new MatchingMnemonic("Dypdyf", new MatchingMnemonicDetail("Double your pleasure, double your fun", "Wrigley’s Doublemint Gum","Slogan")));
//        map.add(new MatchingMnemonic("E", new MatchingMnemonicDetail(" Enjoy", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("EaD", new MatchingMnemonicDetail("Easy as Dell", "Dell Computer","Slogan")));
//        map.add(new MatchingMnemonic("Ef", new MatchingMnemonicDetail("Eat fresh", "Subway","Slogan")));
//        map.add(new MatchingMnemonic("Eif", new MatchingMnemonicDetail("Extinct is forever", "Friends of the Animals","Slogan")));
//        map.add(new MatchingMnemonic("EkbwK", new MatchingMnemonicDetail("Every kiss begins with Kay", "Kay Jewelers","Slogan")));
//        map.add(new MatchingMnemonic("Elh", new MatchingMnemonicDetail("Every little helps", "Tesco","Slogan")));
//        map.add(new MatchingMnemonic("EmPl", new MatchingMnemonicDetail("Expect more Pay less", "Target","Slogan")));
//        map.add(new MatchingMnemonic("Es", new MatchingMnemonicDetail("Experience success", "Salesforce.com","Slogan")));
//        map.add(new MatchingMnemonic("EtIg", new MatchingMnemonicDetail("Empowering the Internet generation", "Cisco Systems","Slogan")));
//        map.add(new MatchingMnemonic("Etr", new MatchingMnemonicDetail("Enjoy the ride", "Nissan","Slogan")));
//        map.add(new MatchingMnemonic("EyawiabAl", new MatchingMnemonicDetail("Everything you always wanted in a beer And less", "Miller Lite","Slogan")));
//        map.add(new MatchingMnemonic("Eyed", new MatchingMnemonicDetail("Express yourself every day", "Philips","Slogan")));
//        map.add(new MatchingMnemonic("Eylac", new MatchingMnemonicDetail("Everything you love about coffee", "Sanka","Slogan")));
//        map.add(new MatchingMnemonic("F", new MatchingMnemonicDetail("Fahrvergnugen", "Volkswagen","Slogan")));
//        map.add(new MatchingMnemonic("Fab", new MatchingMnemonicDetail("Fair and balanced", "Fox News","Slogan")));
//        map.add(new MatchingMnemonic("FAfb", new MatchingMnemonicDetail("Fosters  Australian for beer", "Fosters Australian Beer","Slogan")));
//        map.add(new MatchingMnemonic("Falp", new MatchingMnemonicDetail("For a living planet", "World Wildlife Fund","Slogan")));
//        map.add(new MatchingMnemonic("FaydtBfy", new MatchingMnemonicDetail("For all you do, this Bud’s for you", "Budweiser","Slogan")));
//        map.add(new MatchingMnemonic("Fdlfdd", new MatchingMnemonicDetail("Friends don’t let friends drive drunk", "U.S. Dept. of Transportation","Slogan")));
//        map.add(new MatchingMnemonic("FEETM", new MatchingMnemonicDetail("For Everything Else, There’s MasterCard", "MasterCard","Slogan")));
//        map.add(new MatchingMnemonic("Fewec", new MatchingMnemonicDetail("Free enterprise with every copy", "The Economist","Slogan")));
//        map.add(new MatchingMnemonic("Fewei", new MatchingMnemonicDetail("Free enterprise with every issue", "The Economist","Slogan")));
//        map.add(new MatchingMnemonic("Ff", new MatchingMnemonicDetail("Famously fresh", "Planter’s Peanuts","Slogan")));
//        map.add(new MatchingMnemonic("Ffffr", new MatchingMnemonicDetail("For fast, fast, fast relief", "Anacin","Slogan")));
//        map.add(new MatchingMnemonic("Fg", new MatchingMnemonicDetail("Finger-lickin’ good!", "Kentucky Fried Chicken","Slogan")));
//        map.add(new MatchingMnemonic("Fhabi", new MatchingMnemonicDetail("Ford has a better idea", "Ford","Slogan")));
//        map.add(new MatchingMnemonic("FittrwB", new MatchingMnemonicDetail("Fill it to the rim with Brim", "Brim Decaffeinated Coffee","Slogan")));
//        map.add(new MatchingMnemonic("Fl", new MatchingMnemonicDetail("For life", "Volvo","Slogan")));
//        map.add(new MatchingMnemonic("FmB", new MatchingMnemonicDetail("Flick my Bic", "Bic","Slogan")));
//        map.add(new MatchingMnemonic("Fmwdhttth", new MatchingMnemonicDetail("For men who don’t have to try too hard", "Denim Aftershave","Slogan")));
//        map.add(new MatchingMnemonic("Fnp", new MatchingMnemonicDetail("For negative people", "CameraWorld","Slogan")));
//        map.add(new MatchingMnemonic("FnSs", new MatchingMnemonicDetail("Funny name Serious sandwich", "Schlotzky’s Deli","Slogan")));
//        map.add(new MatchingMnemonic("FtAS", new MatchingMnemonicDetail(" Fueling the American Spirit", "Marathon Petroleum ","Slogan")));
//        map.add(new MatchingMnemonic("Ftfs", new MatchingMnemonicDetail("Fly the friendly skies", "United Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Ftfs(U", new MatchingMnemonicDetail("Fly the friendly skies (of United)", "United Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Ftlosw", new MatchingMnemonicDetail("From the land of sky-blue waters", "Hamm’s Beer","Slogan")));
//        map.add(new MatchingMnemonic("Ftmicoc", new MatchingMnemonicDetail(" For the men in charge of change", "Fortune ","Slogan")));
//        map.add(new MatchingMnemonic("Ftpwhewhee", new MatchingMnemonicDetail("For the person who has everything, we have everything else", "The Sharper Image","Slogan")));
//        map.add(new MatchingMnemonic("Fvsd", new MatchingMnemonicDetail("For virtually spotless dishes", "Cascade","Slogan")));
//        map.add(new MatchingMnemonic("G", new MatchingMnemonicDetail("Grace…pace…pace", "Jaguar","Slogan")));
//        map.add(new MatchingMnemonic("Gahdp", new MatchingMnemonicDetail("Give a hoot, don’t pollute", "U.S. Forest Service","Slogan")));
//        map.add(new MatchingMnemonic("Gapotr", new MatchingMnemonicDetail("Get a piece of the rock", "Prudential","Slogan")));
//        map.add(new MatchingMnemonic("Gigfy", new MatchingMnemonicDetail("Guinness is good for you", "Guinness","Slogan")));
//        map.add(new MatchingMnemonic("Gm", new MatchingMnemonicDetail("Got milk?", "California Milk Processor Board","Slogan")));
//        map.add(new MatchingMnemonic("GmabGmab", new MatchingMnemonicDetail("Give me a break! Give me a break!", "Kit-Kat Bar","Slogan")));
//        map.add(new MatchingMnemonic("Got", new MatchingMnemonicDetail("Get out there", "Royal Caribbean Cruise Lines","Slogan")));
//        map.add(new MatchingMnemonic("GSP", new MatchingMnemonicDetail("Grace Space Pace", "Jaguar","Slogan")));
//        map.add(new MatchingMnemonic("Gtf", new MatchingMnemonicDetail("Get the feeling", "Toyota","Slogan")));
//        map.add(new MatchingMnemonic("Gtietr", new MatchingMnemonicDetail("Good taste is easy to recognize", "Fancy Feast","Slogan")));
//        map.add(new MatchingMnemonic("GtSbtb", new MatchingMnemonicDetail("Grab the Southwest by the bottle", "Pace Picante Sauce","Slogan")));
//        map.add(new MatchingMnemonic("Gttld", new MatchingMnemonicDetail("Good to the last drop", "Maxwell House","Slogan")));
//        map.add(new MatchingMnemonic("Gtwoae", new MatchingMnemonicDetail("Go to work on an egg", "Egg Marketing Board","Slogan")));
//        map.add(new MatchingMnemonic("Gu2mawgytw", new MatchingMnemonicDetail("Give us 20 minutes and we'll give you the world", "WINS Radio, New York","Slogan")));
//        map.add(new MatchingMnemonic("Gyob", new MatchingMnemonicDetail("Get your own box", "Cheez-It","Slogan")));
//        map.add(new MatchingMnemonic("HabhaK", new MatchingMnemonicDetail("Have a break, have a Kitkat", "Kit Kat","Slogan")));
//        map.add(new MatchingMnemonic("Hacas", new MatchingMnemonicDetail("Have a coke and smile", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("HB", new MatchingMnemonicDetail("Hello Boys", "Wonderbra","Slogan")));
//        map.add(new MatchingMnemonic("Hbbr", new MatchingMnemonicDetail("Hand built by robots", "Fiat Strada","Slogan")));
//        map.add(new MatchingMnemonic("Hbsfl", new MatchingMnemonicDetail("Healthy, beautiful smiles for life", "Crest","Slogan")));
//        map.add(new MatchingMnemonic("Hdyfahm", new MatchingMnemonicDetail("How do you feed a hungry man?", "Swanson Hungry-Man","Slogan")));
//        map.add(new MatchingMnemonic("HdysrR", new MatchingMnemonicDetail("How do you spell relief? R-O-L-A-I-D-S", "Rolaids","Slogan")));
//        map.add(new MatchingMnemonic("Hftb", new MatchingMnemonicDetail("Head for the border", "Taco Bell","Slogan")));
//        map.add(new MatchingMnemonic("HGaS", new MatchingMnemonicDetail("Hungry? Grab a Snickers", "Snickers","Slogan")));
//        map.add(new MatchingMnemonic("HHaanHP", new MatchingMnemonicDetail("Hey! How about a nice Hawaiian Punch?", "Hawaiian Punch","Slogan")));
//        map.add(new MatchingMnemonic("HiaccH", new MatchingMnemonicDetail("Happiness is a cigar called Hamlet", "Hamlet","Slogan")));
//        map.add(new MatchingMnemonic("Hiyw", new MatchingMnemonicDetail("Have it your way", "Burder King","Slogan")));
//        map.add(new MatchingMnemonic("HMli", new MatchingMnemonicDetail("Hey, Mikeyhe likes it!", "Life Cereal","Slogan")));
//        map.add(new MatchingMnemonic("Hmv", new MatchingMnemonicDetail("His master’s voice", "Victor Talking Machine Co.","Slogan")));
//        map.add(new MatchingMnemonic("Hpyitds", new MatchingMnemonicDetail("Hertz puts you in the driver’s seat", "Hertz","Slogan")));
//        map.add(new MatchingMnemonic("Hrtpobcr", new MatchingMnemonicDetail("Heineken refreshes the parts other beers cannot reach", "Heineken","Slogan")));
//        map.add(new MatchingMnemonic("Hs", new MatchingMnemonicDetail("Higher standards", "Bank of America","Slogan")));
//        map.add(new MatchingMnemonic("Htatmom", new MatchingMnemonicDetail("Hope, triumph, and the miracle of medicine", "Bristol-Myers Squibb Co.","Slogan")));
//        map.add(new MatchingMnemonic("HtgftlibL", new MatchingMnemonicDetail("Here’s to good friendsTonight, tonight, let it be Lowenbrau", "Lowenbrau Beer","Slogan")));
//        map.add(new MatchingMnemonic("HTgT", new MatchingMnemonicDetail("Hello Tosh, gotta Toshiba?", "Toshiba","Slogan")));
//        map.add(new MatchingMnemonic("Hwdys", new MatchingMnemonicDetail("How well do you share?", "Ricoh","Slogan")));
//        map.add(new MatchingMnemonic("I", new MatchingMnemonicDetail("Innovation", "3M","Slogan")));
//        map.add(new MatchingMnemonic("I", new MatchingMnemonicDetail("Invent", "Hewlett Packard","Slogan")));
//        map.add(new MatchingMnemonic("Iaboaa", new MatchingMnemonicDetail("It’s a bit of an animal", "Peperami","Slogan")));
//        map.add(new MatchingMnemonic("Iagttba", new MatchingMnemonicDetail("It’s a great time to be alive", "Guidant","Slogan")));
//        map.add(new MatchingMnemonic("Iallbtah", new MatchingMnemonicDetail("It’s a lot less bovver than a hover", "Qualcast Concord","Slogan")));
//        map.add(new MatchingMnemonic("Iaphapsap", new MatchingMnemonicDetail("I’m a pepper, he’s a pepper, she’s a pepper", "Dr Pepper","Slogan")));
//        map.add(new MatchingMnemonic("IasH", new MatchingMnemonicDetail("It’s a skoda Honest", "Skoda","Slogan")));
//        map.add(new MatchingMnemonic("IasoBcBsom", new MatchingMnemonicDetail("I am stuck on Band-Aids cause Band-Aids stuck on me", "Band-Aids","Slogan")));
//        map.add(new MatchingMnemonic("Iaw", new MatchingMnemonicDetail("Imagination at work", "General Electric","Slogan")));
//        map.add(new MatchingMnemonic("IawIa", new MatchingMnemonicDetail("I am what I am", "Reebok","Slogan")));
//        map.add(new MatchingMnemonic("IbhdCBL", new MatchingMnemonicDetail("I best he drinks Carling’s Black Label", "Carling Black Label","Slogan")));
//        map.add(new MatchingMnemonic("ICBaIctsbhtriacw", new MatchingMnemonicDetail("I’m Chiquita Banana and I’ve come to say  bananas have to ripen in a certain way", "Chiquita Banana","Slogan")));
//        map.add(new MatchingMnemonic("Icbhtb", new MatchingMnemonicDetail("I can bring home the bacon", "Enjoli","Slogan")));
//        map.add(new MatchingMnemonic("IcbIatwt", new MatchingMnemonicDetail("I can’t believe I ate the whole thing", "Alka-Seltzer","Slogan")));
//        map.add(new MatchingMnemonic("IchaV", new MatchingMnemonicDetail("I coulda had a V-8!", "V-8","Slogan")));
//        map.add(new MatchingMnemonic("Ics", new MatchingMnemonicDetail("Inspiration comes standard", "Chrysler","Slogan")));
//        map.add(new MatchingMnemonic("IDEWiSotT", new MatchingMnemonicDetail("It Does Exactly What it Says on the Tin", "Ronseal","Slogan")));
//        map.add(new MatchingMnemonic("Ieywtb", new MatchingMnemonicDetail("It’s everywhere you want to be", "VISA","Slogan")));
//        map.add(new MatchingMnemonic("IfaIcgu", new MatchingMnemonicDetail("I’ve fallen and I can’t get up", "LifeCall","Slogan")));
//        map.add(new MatchingMnemonic("IfL", new MatchingMnemonicDetail("Ideas for Life", "Panasonic","Slogan")));
//        map.add(new MatchingMnemonic("Ifl", new MatchingMnemonicDetail("Ingredients for life", "Safeway","Slogan")));
//        map.add(new MatchingMnemonic("Igtt", new MatchingMnemonicDetail("It’s good to talk", "British Telecom","Slogan")));
//        map.add(new MatchingMnemonic("IGYW", new MatchingMnemonicDetail("It Gives You Wings!", "Red Bull","Slogan")));
//        map.add(new MatchingMnemonic("Ihr", new MatchingMnemonicDetail("It’s hospital recommended", "Tylenol","Slogan")));
//        map.add(new MatchingMnemonic("II", new MatchingMnemonicDetail("Intel Inside", "Intel","Slogan")));
//        map.add(new MatchingMnemonic("IiAy", new MatchingMnemonicDetail("It is Are you?", "The Independent","Slogan")));
//        map.add(new MatchingMnemonic("IiD", new MatchingMnemonicDetail("Imagine it Done", "Unisys","Slogan")));
//        map.add(new MatchingMnemonic("IigbcigbT", new MatchingMnemonicDetail("If it’s gotta be clean, it’s gotta be Tide", "Tide","Slogan")));
//        map.add(new MatchingMnemonic("Iil", new MatchingMnemonicDetail("Intel inside logo", "Intel","Slogan")));
//        map.add(new MatchingMnemonic("IiloiiM", new MatchingMnemonicDetail("Is it live or is it Memorex?", "Memorex","Slogan")));
//        map.add(new MatchingMnemonic("IiN", new MatchingMnemonicDetail("Impossible is Nothing", "Adidas ","Slogan")));
//        map.add(new MatchingMnemonic("IinSijpod", new MatchingMnemonicDetail("If it’s not SuperSoil, it’s just plain old dirt", "SuperSoil","Slogan")));
//        map.add(new MatchingMnemonic("Iioii", new MatchingMnemonicDetail("If it's on, it's in", "Radio Times","Slogan")));
//        map.add(new MatchingMnemonic("IIoollmliaab", new MatchingMnemonicDetail("If I’ve only one life, let me live it as a blonde", "Clairol","Slogan")));
//        map.add(new MatchingMnemonic("Ijtb", new MatchingMnemonicDetail("It just tastes better", "Burger King","Slogan")));
//        map.add(new MatchingMnemonic("IKGaGaG", new MatchingMnemonicDetail("It Keeps Going, and Going, and Going…", "Energizer","Slogan")));
//        map.add(new MatchingMnemonic("Ili", new MatchingMnemonicDetail("I’m loving it", "McDonalds ","Slogan")));
//        map.add(new MatchingMnemonic("IlismIbtc", new MatchingMnemonicDetail("I liked it so much I bought the company", "Remington","Slogan")));
//        map.add(new MatchingMnemonic("IlNY", new MatchingMnemonicDetail("I love New York", "New York","Slogan")));
//        map.add(new MatchingMnemonic("Iltttwtsiph", new MatchingMnemonicDetail("I’d like to teach the world to sing in perfect harmony", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("Ilwydfm", new MatchingMnemonicDetail("I love what you do for meToyota", "Toyota","Slogan")));
//        map.add(new MatchingMnemonic("IMt", new MatchingMnemonicDetail("It’s Miller time!", "Miller Beer","Slogan")));
//        map.add(new MatchingMnemonic("InajIaa", new MatchingMnemonicDetail("It’s not a job It’s an adventure", "U.S. Navy","Slogan")));
//        map.add(new MatchingMnemonic("Injfba", new MatchingMnemonicDetail("It’s not just for breakfast anymore", "Florida Orange Juice Growers Association","Slogan")));
//        map.add(new MatchingMnemonic("InntfMN", new MatchingMnemonicDetail("It’s not nice to fool Mother Nature", "Chiffon Margarine","Slogan")));
//        map.add(new MatchingMnemonic("InyfOa", new MatchingMnemonicDetail("It’s not your father’s Oldsmobile anymore", "Oldsmobile","Slogan")));
//        map.add(new MatchingMnemonic("Irfts", new MatchingMnemonicDetail("I’d rather fight than switch", "Tareyton Cigarettes","Slogan")));
//        map.add(new MatchingMnemonic("IS", new MatchingMnemonicDetail("It’s Style", "Solex ","Slogan")));
//        map.add(new MatchingMnemonic("ISaBaIh", new MatchingMnemonicDetail("It’s Shake and Bake, and I helped", "Shake and Bake","Slogan")));
//        map.add(new MatchingMnemonic("Isisowawt", new MatchingMnemonicDetail("It’s slinky, it’s slinky, oh what a wonderful toy", "Slinky","Slogan")));
//        map.add(new MatchingMnemonic("Italakot", new MatchingMnemonicDetail("It takes a licking and keeps on ticking", "Timex","Slogan")));
//        map.add(new MatchingMnemonic("Itatmtmatc", new MatchingMnemonicDetail("It takes a tough man to make a tender chicken", "Perdue","Slogan")));
//        map.add(new MatchingMnemonic("Itfc", new MatchingMnemonicDetail("It’s time for clarity", "KPMG","Slogan")));
//        map.add(new MatchingMnemonic("Itrt", new MatchingMnemonicDetail("It’s the real thing", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("IttI", new MatchingMnemonicDetail("I think therefore IBM", "IBM","Slogan")));
//        map.add(new MatchingMnemonic("ItvotjG", new MatchingMnemonicDetail("In the valley of the jolly--ho-ho-ho!--Green Giant", "Green Giant","Slogan")));
//        map.add(new MatchingMnemonic("Iwamfac", new MatchingMnemonicDetail("I’d walk a mile for a camel", "Camel","Slogan")));
//        map.add(new MatchingMnemonic("Iwc", new MatchingMnemonicDetail("Invest with confidence", "T. Rowe Price","Slogan")));
//        map.add(new MatchingMnemonic("IwIwaOMW", new MatchingMnemonicDetail("I wish I were an Oscar Mayer Wiener", "Oscar Mayer","Slogan")));
//        map.add(new MatchingMnemonic("IwmM", new MatchingMnemonicDetail("I want my Maypo", "Maypo","Slogan")));
//        map.add(new MatchingMnemonic("Iwyraf", new MatchingMnemonicDetail("It's what your right arm's for", "Courage Tavern Ale","Slogan")));
//        map.add(new MatchingMnemonic("Iygttwgtb", new MatchingMnemonicDetail("If you’ve got the time, we’ve got the beer", "Miller Beer","Slogan")));
//        map.add(new MatchingMnemonic("Iywtcsaw", new MatchingMnemonicDetail("If you want to capture someone’s attention, whisper", "Coty Perfume","Slogan")));
//        map.add(new MatchingMnemonic("Iywtgagah", new MatchingMnemonicDetail("If you want to get ahead, get a hat", "Hat Council","Slogan")));
//        map.add(new MatchingMnemonic("Jb", new MatchingMnemonicDetail("Jack’s back!", "Jack in the Box","Slogan")));
//        map.add(new MatchingMnemonic("Jdi", new MatchingMnemonicDetail("Just do it", "Nike","Slogan")));
//        map.add(new MatchingMnemonic("JftfoiDC", new MatchingMnemonicDetail("Just for the fun of it, Diet Coke", "Diet Coke","Slogan")));
//        map.add(new MatchingMnemonic("JfttoiDC", new MatchingMnemonicDetail("Just for the taste of it, Diet Coke", "Diet Coke","Slogan")));
//        map.add(new MatchingMnemonic("Jmmmatwmmg", new MatchingMnemonicDetail("Jell-O makes me mellow and the wiggle makes me giggle", "Jell-O","Slogan")));
//        map.add(new MatchingMnemonic("Kgagag", new MatchingMnemonicDetail("Keeps going and going and going", "Energizer","Slogan")));
//        map.add(new MatchingMnemonic("KtMa", new MatchingMnemonicDetail("Kid tested Mother approved", "Kix Cereal","Slogan")));
//        map.add(new MatchingMnemonic("Ktsc", new MatchingMnemonicDetail("Keep that schoolgirl complexion", "Palmolive Soap","Slogan")));
//        map.add(new MatchingMnemonic("LagnSFit", new MatchingMnemonicDetail("Like a good neighbor, State Farm is there", "State Farm","Slogan")));
//        map.add(new MatchingMnemonic("Lar", new MatchingMnemonicDetail("Like a rock", "Chevy Trucks","Slogan")));
//        map.add(new MatchingMnemonic("Las", new MatchingMnemonicDetail("Lifts and separates", "Playtex Cross-Your-Heart Bra","Slogan")));
//        map.add(new MatchingMnemonic("Lifl", new MatchingMnemonicDetail("Love it for life", "Dannon Yogurt","Slogan")));
//        map.add(new MatchingMnemonic("LiywPio", new MatchingMnemonicDetail(" Live in your world Play in ours", "PlayStation ","Slogan")));
//        map.add(new MatchingMnemonic("LmCiu", new MatchingMnemonicDetail("Life’s messy Clean it up!", "Bissell","Slogan")));
//        map.add(new MatchingMnemonic("LMnc", new MatchingMnemonicDetail("Look, Ma, no cavities!", "Crest","Slogan")));
//        map.add(new MatchingMnemonic("Lr", new MatchingMnemonicDetail("Legendary reliability", "APC","Slogan")));
//        map.add(new MatchingMnemonic("Lr", new MatchingMnemonicDetail("Live richly", "Citi","Slogan")));
//        map.add(new MatchingMnemonic("Lsfs", new MatchingMnemonicDetail("Look sharp, feel sharp", "Gillette","Slogan")));
//        map.add(new MatchingMnemonic("LSmft", new MatchingMnemonicDetail("Lucky Strike means fine tobacco", "Lucky Strike","Slogan")));
//        map.add(new MatchingMnemonic("LtamgchfvP", new MatchingMnemonicDetail("Lipsmackin’ thirstquenchin’ acetastin’ motivatin’ goodbuzzin’ cooltalkin’ highwalkin’ fastlivin’ vergivin’coolfizzin’ Pepsi", "Pepsi Cola","Slogan")));
//        map.add(new MatchingMnemonic("LtcNtt", new MatchingMnemonicDetail("Lose the carbs Not the taste", "Michelob Ultra","Slogan")));
//        map.add(new MatchingMnemonic("Ltdtu", new MatchingMnemonicDetail("Leave the driving to us", "Greyhound","Slogan")));
//        map.add(new MatchingMnemonic("Ltlol", new MatchingMnemonicDetail("Lick the lid of llife", "Muller","Slogan")));
//        map.add(new MatchingMnemonic("Lyfdtw", new MatchingMnemonicDetail("Let your fingers do the walking", "Yellow Pages","Slogan")));
//        map.add(new MatchingMnemonic("MB", new MatchingMnemonicDetail("Make Believe", "Sony ","Slogan")));
//        map.add(new MatchingMnemonic("MbhafniO", new MatchingMnemonicDetail("My bologna has a first name, it’s O-S-C-A-R", "Oscar Mayer","Slogan")));
//        map.add(new MatchingMnemonic("MCwcywhaetii", new MatchingMnemonicDetail("Mr Clean will clean your whole house and everything that’s in it", "Mr. Clean","Slogan")));
//        map.add(new MatchingMnemonic("Md", new MatchingMnemonicDetail("Magically delicious", "Lucky Charms","Slogan")));
//        map.add(new MatchingMnemonic("MftbsoE", new MatchingMnemonicDetail("Made from the best stuff on Earth", "Snapple","Slogan")));
//        map.add(new MatchingMnemonic("Mglb", new MatchingMnemonicDetail("Milk’s gotta lotta bottle", "Milk Marketing Board","Slogan")));
//        map.add(new MatchingMnemonic("MiboA", new MatchingMnemonicDetail("Merrill-Lynch is bullish on America", "Merrill-Lynch","Slogan")));
//        map.add(new MatchingMnemonic("Miymniyh", new MatchingMnemonicDetail("Melts in your mouth, not in your hands", "M&Ms","Slogan")));
//        map.add(new MatchingMnemonic("MLiboA", new MatchingMnemonicDetail("Merrill Lynch is bullish on America", "Merrill Lynch","Slogan")));
//        map.add(new MatchingMnemonic("MlMc", new MatchingMnemonicDetail("My life My card", "American Express","Slogan")));
//        map.add(new MatchingMnemonic("MMG", new MatchingMnemonicDetail("M’m! M’m! Good!", "Campbell’s Soup","Slogan")));
//        map.add(new MatchingMnemonic("Mmgm", new MatchingMnemonicDetail("MGM means great movies", "MGM","Slogan")));
//        map.add(new MatchingMnemonic("Mmmm", new MatchingMnemonicDetail("Meow, meow, meow, meow", "Meow Mix (Ralston)","Slogan")));
//        map.add(new MatchingMnemonic("Mmmmm", new MatchingMnemonicDetail("M’m, m’m, m’m, m’m, m’mtoasty!", "Quiznos","Slogan")));
//        map.add(new MatchingMnemonic("Mmtsm", new MatchingMnemonicDetail("Mama mia, thatsa spicy meatball", "Alka-Seltzer","Slogan")));
//        map.add(new MatchingMnemonic("MsbwiMiM", new MatchingMnemonicDetail("Maybe she’s born with it Maybe it’s Maybelline", "Maybelline","Slogan")));
//        map.add(new MatchingMnemonic("MsT", new MatchingMnemonicDetail("Must see TV", "NBC","Slogan")));
//        map.add(new MatchingMnemonic("Mtmon", new MatchingMnemonicDetail("Make the most of now", "Vodafone","Slogan")));
//        map.add(new MatchingMnemonic("MwItIkh", new MatchingMnemonicDetail("My wife, I think I’ll keep her", "Geritol","Slogan")));
//        map.add(new MatchingMnemonic("Mwm", new MatchingMnemonicDetail("Medicine with muscle", "Motrin","Slogan")));
//        map.add(new MatchingMnemonic("MybIlit", new MatchingMnemonicDetail("Manly yes, but I like it, too", "Irish Spring Soap","Slogan")));
//        map.add(new MatchingMnemonic("NcbmamC", new MatchingMnemonicDetail("Nothing comes between me and my Calvins", "Calvin Klein Jeans","Slogan")));
//        map.add(new MatchingMnemonic("Ncbtd", new MatchingMnemonicDetail("No child born to die", "Save The Children","Slogan")));
//        map.add(new MatchingMnemonic("NdclK", new MatchingMnemonicDetail("Nobody does chicken like KFC", "Kentucky Fried Chicken","Slogan")));
//        map.add(new MatchingMnemonic("NdlSL", new MatchingMnemonicDetail("Nobody doesn’t like Sara Lee", "Sara Lee Foods","Slogan")));
//        map.add(new MatchingMnemonic("Nf", new MatchingMnemonicDetail("Never follow", "Audi","Slogan")));
//        map.add(new MatchingMnemonic("NFnc", new MatchingMnemonicDetail("No FT, no comment", "Financial Times","Slogan")));
//        map.add(new MatchingMnemonic("Nioys", new MatchingMnemonicDetail("Nationwide is on your side", "Nationwide Insurance","Slogan")));
//        map.add(new MatchingMnemonic("NKU", new MatchingMnemonicDetail("Never Knowingly Undersold", "John Lewis","Slogan")));
//        map.add(new MatchingMnemonic("Nlesys", new MatchingMnemonicDetail("Never let em see you sweat", "Gillette Dry idea","Slogan")));
//        map.add(new MatchingMnemonic("Nmt", new MatchingMnemonicDetail("No more tears", "Johnson’s Baby Shampoo","Slogan")));
//        map.add(new MatchingMnemonic("NNmtvb", new MatchingMnemonicDetail("N-E-S-T-L-E-S, Nestles makes the very bestchocolate", "Nestles","Slogan")));
//        map.add(new MatchingMnemonic("NrJr", new MatchingMnemonicDetail("No rules Just right", "Outback Steakhouse","Slogan")));
//        map.add(new MatchingMnemonic("NrlaD", new MatchingMnemonicDetail("Nothing runs like a Deere", "John Deere","Slogan")));
//        map.add(new MatchingMnemonic("NslaE", new MatchingMnemonicDetail("Nothing sucks like an Electrolux", "Electrolux","Slogan")));
//        map.add(new MatchingMnemonic("Nsllsfto", new MatchingMnemonicDetail("Nothin’ says lovin’ like somethin’ from the oven", "Pillsbury","Slogan")));
//        map.add(new MatchingMnemonic("Ntb", new MatchingMnemonicDetail("Now, that’s better", "SPRINT PCS","Slogan")));
//        map.add(new MatchingMnemonic("OaJaapoac", new MatchingMnemonicDetail(" Own a Jaguar at a price of a car", "Jaguar ","Slogan")));
//        map.add(new MatchingMnemonic("ObitAd", new MatchingMnemonicDetail("Our business is the American dream", "FannieMae","Slogan")));
//        map.add(new MatchingMnemonic("Ocaat", new MatchingMnemonicDetail("One client at a time", "MorganStanley","Slogan")));
//        map.add(new MatchingMnemonic("OffakNL", new MatchingMnemonicDetail("Only fit for a king Nine Lives", "Nine Lives Cat Food","Slogan")));
//        map.add(new MatchingMnemonic("OH", new MatchingMnemonicDetail(" Open Happiness", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("OIa", new MatchingMnemonicDetail("Ore-Ida! It’s all-righta!", "Ore-Ida","Slogan")));
//        map.add(new MatchingMnemonic("Oratlgit", new MatchingMnemonicDetail("Our repairmen are the loneliest guys in town", "Maytag Appliances","Slogan")));
//        map.add(new MatchingMnemonic("Oycpff", new MatchingMnemonicDetail("Only you can prevent forest fires", "U.S. Forest Service","Slogan")));
//        map.add(new MatchingMnemonic("Oyt", new MatchingMnemonicDetail("Obey your thirst", "Sprite","Slogan")));
//        map.add(new MatchingMnemonic("PaTiyt", new MatchingMnemonicDetail("Put a Tiger in your tank", "Esso","Slogan")));
//        map.add(new MatchingMnemonic("Pbas", new MatchingMnemonicDetail(" Power, beauty and soul", "Aston Martin ","Slogan")));
//        map.add(new MatchingMnemonic("Pbp", new MatchingMnemonicDetail(" Push button publishing", "Blogger ","Slogan")));
//        map.add(new MatchingMnemonic("PcpI", new MatchingMnemonicDetail("Pure clean, pure Ivory", "Ivory Soap","Slogan")));
//        map.add(new MatchingMnemonic("PcsfH", new MatchingMnemonicDetail("Pure cane sugar from Hawaii", "C&H","Slogan")));
//        map.add(new MatchingMnemonic("PdstC", new MatchingMnemonicDetail("Please don’t squeeze the Charmin", "Charmin","Slogan")));
//        map.add(new MatchingMnemonic("PFr", new MatchingMnemonicDetail("Pepperidge Farm remembers", "Pepperidge Farm","Slogan")));
//        map.add(new MatchingMnemonic("Pftr", new MatchingMnemonicDetail("Passion for the road", "Mazda","Slogan")));
//        map.add(new MatchingMnemonic("Pftwty", new MatchingMnemonicDetail("Pepsi, for those who think young", "Pepsi","Slogan")));
//        map.add(new MatchingMnemonic("Phts", new MatchingMnemonicDetail("Pepsi-Cola hits the spot", "Pepsi","Slogan")));
//        map.add(new MatchingMnemonic("Phts", new MatchingMnemonicDetail("Pepsi hits the spot", "Pepsi","Slogan")));
//        map.add(new MatchingMnemonic("PLG", new MatchingMnemonicDetail("Play Laugh Grow", "Fisher-Price","Slogan")));
//        map.add(new MatchingMnemonic("PmdyhaGP", new MatchingMnemonicDetail("Pardon me, do you have any Grey Poupon?", "Grey Poupon","Slogan")));
//        map.add(new MatchingMnemonic("Ppffowarii", new MatchingMnemonicDetail("Plop plop, fizz fizz, oh what a relief it is", "Alka-Seltzer","Slogan")));
//        map.add(new MatchingMnemonic("PpffowariiPpff", new MatchingMnemonicDetail("Plop, plop, fizz, fizz, oh what a relief it is Plink, plink, fizz, fizz", "Alka Seltzer","Slogan")));
//        map.add(new MatchingMnemonic("Pptwo", new MatchingMnemonicDetail("Pleasing people the world over", "Holiday Inn","Slogan")));
//        map.add(new MatchingMnemonic("Ptbabl", new MatchingMnemonicDetail("Preparing to be a beautiful lady", "Pears Soap","Slogan")));
//        map.add(new MatchingMnemonic("Ptbbitw", new MatchingMnemonicDetail("Probably the best beer in the world", "Carlsberg","Slogan")));
//        map.add(new MatchingMnemonic("PTowm", new MatchingMnemonicDetail("Pork The other white meat", "National Pork Board","Slogan")));
//        map.add(new MatchingMnemonic("Ptwty", new MatchingMnemonicDetail("PepsiŃfor those who think young", "Pepsi","Slogan")));
//        map.add(new MatchingMnemonic("Qiewd", new MatchingMnemonicDetail("Quality in everything we do", "Ernst & Young","Slogan")));
//        map.add(new MatchingMnemonic("Qijo", new MatchingMnemonicDetail("Quality is job one", "Ford","Slogan")));
//        map.add(new MatchingMnemonic("Qngoos", new MatchingMnemonicDetail("Quality never goes out of style", "Levis","Slogan")));
//        map.add(new MatchingMnemonic("Ratc", new MatchingMnemonicDetail("Ring around the collar", "Wisk Laundry Detergent","Slogan")));
//        map.add(new MatchingMnemonic("Rbg", new MatchingMnemonicDetail("Rare but good", "Imperial Leather","Slogan")));
//        map.add(new MatchingMnemonic("RE", new MatchingMnemonicDetail("Reassuringly Expensive", "Stella Artois","Slogan")));
//        map.add(new MatchingMnemonic("RiF", new MatchingMnemonicDetail("Relax, it’s FedEx", "FedEx","Slogan")));
//        map.add(new MatchingMnemonic("Rkbd", new MatchingMnemonicDetail("RAID kills bugs dead", "RAID","Slogan")));
//        map.add(new MatchingMnemonic("Roats", new MatchingMnemonicDetail("Reach out and touch someone", "AT&T","Slogan")));
//        map.add(new MatchingMnemonic("Rtjom", new MatchingMnemonicDetail("Restoring the joy of motion", "DePuy Orthopedics","Slogan")));
//        map.add(new MatchingMnemonic("Rtl", new MatchingMnemonicDetail("Ride the light", "Qwest","Slogan")));
//        map.add(new MatchingMnemonic("RtSFt", new MatchingMnemonicDetail("Rice-a-Roni, the San Francisco treat", "Rice-a-Roni","Slogan")));
//        map.add(new MatchingMnemonic("Ryhiys", new MatchingMnemonicDetail("Raise your hand if you’re sure", "Sure","Slogan")));
//        map.add(new MatchingMnemonic("S", new MatchingMnemonicDetail("SchhhYou-Know-Who", "Schweppes","Slogan")));
//        map.add(new MatchingMnemonic("Saoit", new MatchingMnemonicDetail("Slightly ahead of its time", "Panasonic","Slogan")));
//        map.add(new MatchingMnemonic("Sas", new MatchingMnemonicDetail("Start aging smart", "Kellogg’s Smart Start","Slogan")));
//        map.add(new MatchingMnemonic("SCp", new MatchingMnemonicDetail("Snap! Crackle! pop!", "Kellogg’s Rice Krispies","Slogan")));
//        map.add(new MatchingMnemonic("SCSwtttgntwgt", new MatchingMnemonicDetail("Sorry, Charlie Starkist wants tuna that tastes good, not tuna with good taste", "Starkist Tuna","Slogan")));
//        map.add(new MatchingMnemonic("SD", new MatchingMnemonicDetail(" Seafood Differently", "Red Lobster ","Slogan")));
//        map.add(new MatchingMnemonic("Sdp", new MatchingMnemonicDetail("Sheer driving pleasure", "BMW","Slogan")));
//        map.add(new MatchingMnemonic("Sefambmfaw", new MatchingMnemonicDetail("Strong enough for a man, but made for a woman", "Secret Deodorant","Slogan")));
//        map.add(new MatchingMnemonic("Sfasp", new MatchingMnemonicDetail("Solutions for a small planet", "IBM","Slogan")));
//        map.add(new MatchingMnemonic("Sgyagwtf", new MatchingMnemonicDetail("Singapore girl, you’re a great way to fly", "Singapore Airlines","Slogan")));
//        map.add(new MatchingMnemonic("SIaMG", new MatchingMnemonicDetail(" Success It’s a Mind Game", "Tag Heuer ","Slogan")));
//        map.add(new MatchingMnemonic("Siwf", new MatchingMnemonicDetail("Say it with flowers", "FTD","Slogan")));
//        map.add(new MatchingMnemonic("SMLB", new MatchingMnemonicDetail("Save Money Live Better", "Walmart","Slogan")));
//        map.add(new MatchingMnemonic("SmSl", new MatchingMnemonicDetail(" Share moments Share life", "Kodak ","Slogan")));
//        map.add(new MatchingMnemonic("Soobmaw", new MatchingMnemonicDetail("Some of our best men are women", "U.S. Army","Slogan")));
//        map.add(new MatchingMnemonic("Sos", new MatchingMnemonicDetail("Spirit of service", "Qwest","Slogan")));
//        map.add(new MatchingMnemonic("SptI", new MatchingMnemonicDetail("Software powers the Internet", "Oracle","Slogan")));
//        map.add(new MatchingMnemonic("Srtafk", new MatchingMnemonicDetail("Silly rabbit, trix are for kids", "Trix Cereal","Slogan")));
//        map.add(new MatchingMnemonic("Ssita", new MatchingMnemonicDetail("Something special in the air", "American Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Std", new MatchingMnemonicDetail("Stronger than dirt", "Ajax","Slogan")));
//        map.add(new MatchingMnemonic("Stsa", new MatchingMnemonicDetail("Something to smile about", "Quaker Oatmeal","Slogan")));
//        map.add(new MatchingMnemonic("StUiyC", new MatchingMnemonicDetail("See the USA in your Chevrolet", "Chevrolet","Slogan")));
//        map.add(new MatchingMnemonic("Swwm", new MatchingMnemonicDetail(" See what we mean", "Canon ","Slogan")));
//        map.add(new MatchingMnemonic("SybbaGb", new MatchingMnemonicDetail("Shouldn’t your baby be a Gerber baby?", "Gerber","Slogan")));
//        map.add(new MatchingMnemonic("Syflansyd", new MatchingMnemonicDetail("Sometimes you feel like a nut, sometimes you don't", "Peter Paul Mounds/ Almond Joy","Slogan")));
//        map.add(new MatchingMnemonic("SYkw", new MatchingMnemonicDetail("Schhh! You know who?", "Schweppes","Slogan")));
//        map.add(new MatchingMnemonic("Sywf", new MatchingMnemonicDetail("See your way forward", "Epiphany","Slogan")));
//        map.add(new MatchingMnemonic("T", new MatchingMnemonicDetail("Thrive", "Kaiser Permanente","Slogan")));
//        map.add(new MatchingMnemonic("Tabooc", new MatchingMnemonicDetail("Take a bite out of crime", "National Crime Prevention Council","Slogan")));
//        map.add(new MatchingMnemonic("Tafc", new MatchingMnemonicDetail("The antidote for civilization", "Club Med","Slogan")));
//        map.add(new MatchingMnemonic("Talakot", new MatchingMnemonicDetail("Takes a licking and keeps on ticking", "Timex","Slogan")));
//        map.add(new MatchingMnemonic("Tapsslcpooassb", new MatchingMnemonicDetail("Two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun", "McDonald’s","Slogan")));
//        map.add(new MatchingMnemonic("TarfJ", new MatchingMnemonicDetail("There’s always room for J-E-L-L-0", "Jell-O","Slogan")));
//        map.add(new MatchingMnemonic("TasttmcbFeetM", new MatchingMnemonicDetail("There are some things that money can’t buy For everything else there’s MasterCard", "MasterCard","Slogan")));
//        map.add(new MatchingMnemonic("Tb", new MatchingMnemonicDetail("Think big", "Imax","Slogan")));
//        map.add(new MatchingMnemonic("Tbamcg", new MatchingMnemonicDetail("The best a man can get", "Gillette","Slogan")));
//        map.add(new MatchingMnemonic("TbkasiA", new MatchingMnemonicDetail("The best kept automotive secret in America", "Peugeot","Slogan")));
//        map.add(new MatchingMnemonic("Tboc", new MatchingMnemonicDetail("The breakfast of champions", "Wheaties","Slogan")));
//        map.add(new MatchingMnemonic("TbpowuiFiyc", new MatchingMnemonicDetail("The best part of waking up is Folger’s in your cup", "Folger’s Coffee","Slogan")));
//        map.add(new MatchingMnemonic("TbtitwhGwaot", new MatchingMnemonicDetail("The best tires in the world have Goodyear written all over them", "Goodyear","Slogan")));
//        map.add(new MatchingMnemonic("TbtmMf", new MatchingMnemonicDetail("The beer that made Milwaukee famous", "Schlitz","Slogan")));
//        map.add(new MatchingMnemonic("Tciaacr", new MatchingMnemonicDetail(" The customer is always and completely right!", "Marks & Spencer ","Slogan")));
//        map.add(new MatchingMnemonic("TcifiaT", new MatchingMnemonicDetail("The car in front is a Toyota", "Toyota","Slogan")));
//        map.add(new MatchingMnemonic("TCns", new MatchingMnemonicDetail("The Citi never sleeps", "Citibank","Slogan")));
//        map.add(new MatchingMnemonic("Tcob", new MatchingMnemonicDetail("Taking care of business", "Office Depot","Slogan")));
//        map.add(new MatchingMnemonic("Tcobb", new MatchingMnemonicDetail("The champagne of bottled beer", "Miller High Life","Slogan")));
//        map.add(new MatchingMnemonic("Td", new MatchingMnemonicDetail("Think different", "Apple Computer","Slogan")));
//        map.add(new MatchingMnemonic("TfbTfO", new MatchingMnemonicDetail("The future’s bright The future’s Orange", "Orange","Slogan")));
//        map.add(new MatchingMnemonic("Tfdi", new MatchingMnemonicDetail("The fun develops instantly", "Polaroid","Slogan")));
//        map.add(new MatchingMnemonic("Tfsb", new MatchingMnemonicDetail("The flavor says butter", "Parkay Margarine","Slogan")));
//        map.add(new MatchingMnemonic("TftptM", new MatchingMnemonicDetail("The few, the proud, the Marines", "U.S. Marines","Slogan")));
//        map.add(new MatchingMnemonic("TG", new MatchingMnemonicDetail("They’re GR-R-R-reat", "Kelloggs Frosties","Slogan")));
//        map.add(new MatchingMnemonic("TgbwC", new MatchingMnemonicDetail("Things go better with Coke", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("Tglf", new MatchingMnemonicDetail("Tastes great, less filling", "Miller Lite","Slogan")));
//        map.add(new MatchingMnemonic("Tgtii", new MatchingMnemonicDetail("The greatest tragedy is indifference", "Red Cross","Slogan")));
//        map.add(new MatchingMnemonic("Tgtii", new MatchingMnemonicDetail(" The greatest tragedy is indifference", "Red Cross ","Slogan")));
//        map.add(new MatchingMnemonic("Thpoe", new MatchingMnemonicDetail("The happiest place on earth", "Disneyland","Slogan")));
//        map.add(new MatchingMnemonic("Tiao", new MatchingMnemonicDetail("Take it all off", "Noxzema","Slogan")));
//        map.add(new MatchingMnemonic("Tiee", new MatchingMnemonicDetail("The incredible, edible egg", "American Egg Board","Slogan")));
//        map.add(new MatchingMnemonic("Tins", new MatchingMnemonicDetail(" There is no substitute", "Porsche ","Slogan")));
//        map.add(new MatchingMnemonic("TiybTiybod", new MatchingMnemonicDetail("This is your brain This is your brain on drugs", "Partnership for a Drug-Free America","Slogan")));
//        map.add(new MatchingMnemonic("Tiyli", new MatchingMnemonicDetail("Try it, you’ll like it", "Alka-Seltzer","Slogan")));
//        map.add(new MatchingMnemonic("Tkob", new MatchingMnemonicDetail("The king of beers", "Budweiser","Slogan")));
//        map.add(new MatchingMnemonic("Tlpywtg", new MatchingMnemonicDetail("The last place you want to go", "Dixons","Slogan")));
//        map.add(new MatchingMnemonic("Tmcmiymniyh", new MatchingMnemonicDetail("The milk chocolate melts in your mouth, not in your hand", "M&M","Slogan")));
//        map.add(new MatchingMnemonic("Tmiatttw", new MatchingMnemonicDetail("The mind is a terrible thing to waste", "United Negro College Fund","Slogan")));
//        map.add(new MatchingMnemonic("Tmoam", new MatchingMnemonicDetail("The mark of a man", "Old Spice","Slogan")));
//        map.add(new MatchingMnemonic("Tmos", new MatchingMnemonicDetail("The miracles of science", "DuPont","Slogan")));
//        map.add(new MatchingMnemonic("Tmtnin", new MatchingMnemonicDetail("The most trusted name in news", "CNN","Slogan")));
//        map.add(new MatchingMnemonic("TMUoMUA", new MatchingMnemonicDetail("The Make Up of Make Up Artists", "Max Factor","Slogan")));
//        map.add(new MatchingMnemonic("Tne", new MatchingMnemonicDetail("There’s no equal", "Sweet ‘N Low","Slogan")));
//        map.add(new MatchingMnemonic("Tnitc", new MatchingMnemonicDetail("The network is the computer", "Sun Microsystems","Slogan")));
//        map.add(new MatchingMnemonic("Tns", new MatchingMnemonicDetail("The next stage", "Wells Fargo","Slogan")));
//        map.add(new MatchingMnemonic("Tnsscashfsycrm", new MatchingMnemonicDetail("The nighttime sniffling sneezing coughing aching stuffy head fever so you can rest medicine", "NyQuil","Slogan")));
//        map.add(new MatchingMnemonic("Totb", new MatchingMnemonicDetail("Think outside the box", "Apple Computer","Slogan")));
//        map.add(new MatchingMnemonic("Totb", new MatchingMnemonicDetail("Think outside the bun", "Taco Bell","Slogan")));
//        map.add(new MatchingMnemonic("Tpie", new MatchingMnemonicDetail("Turning partnership into energy", "ChevronTexaco","Slogan")));
//        map.add(new MatchingMnemonic("Tpoaou", new MatchingMnemonicDetail("The power of all of us", "eBay","Slogan")));
//        map.add(new MatchingMnemonic("Tpod", new MatchingMnemonicDetail("The power of dreams", "Honda","Slogan")));
//        map.add(new MatchingMnemonic("Tptbyb", new MatchingMnemonicDetail("The power to be your best", "Apple Computer","Slogan")));
//        map.add(new MatchingMnemonic("Tptr", new MatchingMnemonicDetail("The pause that refreshes", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("Tqgibtngo", new MatchingMnemonicDetail("The quality goes in before the name goes on", "Zenith","Slogan")));
//        map.add(new MatchingMnemonic("Tqp", new MatchingMnemonicDetail("The quicker picker-upper", "Bounty","Slogan")));
//        map.add(new MatchingMnemonic("Trgo", new MatchingMnemonicDetail("The relief goes on", "Allegra","Slogan")));
//        map.add(new MatchingMnemonic("Trpop", new MatchingMnemonicDetail("The relentless pursuit of perfection", "Lexus","Slogan")));
//        map.add(new MatchingMnemonic("Trrie", new MatchingMnemonicDetail("The right relationship is everything", "JPMorgan Chase Bank","Slogan")));
//        map.add(new MatchingMnemonic("Trwnbts", new MatchingMnemonicDetail("The road will never be the same", "Acura","Slogan")));
//        map.add(new MatchingMnemonic("TS", new MatchingMnemonicDetail("Think Small", "Volkswagen","Slogan")));
//        map.add(new MatchingMnemonic("Tsb", new MatchingMnemonicDetail("The silver bullet", "Coors","Slogan")));
//        map.add(new MatchingMnemonic("Tsfcat", new MatchingMnemonicDetail("The source for computing and technology", "CNET","Slogan")));
//        map.add(new MatchingMnemonic("Tsgcafibn", new MatchingMnemonicDetail("Tastes so good cats ask for it by name", "Meow Mix","Slogan")));
//        map.add(new MatchingMnemonic("Tso7", new MatchingMnemonicDetail("The spirit of 76", "Unocal","Slogan")));
//        map.add(new MatchingMnemonic("Ttctr", new MatchingMnemonicDetail(" Twist the cap to refreshment", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("Ttf", new MatchingMnemonicDetail("Time to fly", "United Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Ttjyel", new MatchingMnemonicDetail("The toughest job you’ll ever love", "U.S. Peace Corps","Slogan")));
//        map.add(new MatchingMnemonic("TTl", new MatchingMnemonicDetail("Talk They’ll listen", "Philip Morris","Slogan")));
//        map.add(new MatchingMnemonic("Ttmtd", new MatchingMnemonicDetail("Time to make the doughnuts", "Dunkin Donuts","Slogan")));
//        map.add(new MatchingMnemonic("Ttoang", new MatchingMnemonicDetail("The taste of a new generation", "Pepsi","Slogan")));
//        map.add(new MatchingMnemonic("TtR", new MatchingMnemonicDetail("Taste the Rainbow", "Skittles","Slogan")));
//        map.add(new MatchingMnemonic("TtttT", new MatchingMnemonicDetail("Tum, tum, tum, tum, Tums", "Tums","Slogan")));
//        map.add(new MatchingMnemonic("Tu", new MatchingMnemonicDetail("The uncola", "7-Up","Slogan")));
//        map.add(new MatchingMnemonic("Tudm", new MatchingMnemonicDetail("The ultimate driving machine", "BMW","Slogan")));
//        map.add(new MatchingMnemonic("Twe", new MatchingMnemonicDetail("That was easy", "Staples","Slogan")));
//        map.add(new MatchingMnemonic("Twfa", new MatchingMnemonicDetail("The world’s favourite airline", "British Airways","Slogan")));
//        map.add(new MatchingMnemonic("Twlb", new MatchingMnemonicDetail("The world’s local bank", "HSBC","Slogan")));
//        map.add(new MatchingMnemonic("Twnc", new MatchingMnemonicDetail("The world’s networking company", "AT&T","Slogan")));
//        map.add(new MatchingMnemonic("Twom", new MatchingMnemonicDetail("The world’s online marketplace", "eBay","Slogan")));
//        map.add(new MatchingMnemonic("Twot", new MatchingMnemonicDetail("The world on time", "FedEx","Slogan")));
//        map.add(new MatchingMnemonic("Twtf", new MatchingMnemonicDetail("The way to fly", "British Airways","Slogan")));
//        map.add(new MatchingMnemonic("Twttw", new MatchingMnemonicDetail("Two words to the wise", "Georgia Federal","Slogan")));
//        map.add(new MatchingMnemonic("Tyfys", new MatchingMnemonicDetail("Thank you for your support", "Bartles & Jaymes","Slogan")));
//        map.add(new MatchingMnemonic("UoS", new MatchingMnemonicDetail("Uh, oh, Spaghettios", "Spaghettios","Slogan")));
//        map.add(new MatchingMnemonic("VDT", new MatchingMnemonicDetail("Vorsprung Durch Technik", "Audi","Slogan")));
//        map.add(new MatchingMnemonic("Vgtro", new MatchingMnemonicDetail("Visine gets the red out", "Visine","Slogan")));
//        map.add(new MatchingMnemonic("Vifl", new MatchingMnemonicDetail("Virginia is for lovers", "The Virginia Tourism Commission","Slogan")));
//        map.add(new MatchingMnemonic("W", new MatchingMnemonicDetail("Wassup?!", "Budweiser","Slogan")));
//        map.add(new MatchingMnemonic("W", new MatchingMnemonicDetail("WotalotIgot!", "Smarties","Slogan")));
//        map.add(new MatchingMnemonic("WaaaK", new MatchingMnemonicDetail("We all adore a Kia-Ora", "Kia-Ora","Slogan")));
//        map.add(new MatchingMnemonic("WanlSihtbg", new MatchingMnemonicDetail("With a name like Smucker’s, it has to be good", "Smucker’s","Slogan")));
//        map.add(new MatchingMnemonic("Wataha", new MatchingMnemonicDetail("We answer to a higher authority", "Hebrew National","Slogan")));
//        map.add(new MatchingMnemonic("WAtowtf", new MatchingMnemonicDetail("Western Airlines the only way to fly", "Western Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Wbcyw", new MatchingMnemonicDetail("When banks compete, you win", "LendingTree","Slogan")));
//        map.add(new MatchingMnemonic("Wbgttl", new MatchingMnemonicDetail("We bring good things to life", "GE (General Electric)","Slogan")));
//        map.add(new MatchingMnemonic("Wbgttl", new MatchingMnemonicDetail("We bring good things to life", "General Electric","Slogan")));
//        map.add(new MatchingMnemonic("Wbyesotw", new MatchingMnemonicDetail("We’re behind you every step of the way", "Huggies","Slogan")));
//        map.add(new MatchingMnemonic("WcBdfy", new MatchingMnemonicDetail("What can Brown do for you?", "UPS","Slogan")));
//        map.add(new MatchingMnemonic("Wcn", new MatchingMnemonicDetail("We’re cooking now", "Denny’s","Slogan")));
//        map.add(new MatchingMnemonic("Wdywtgt", new MatchingMnemonicDetail("Where do you want to go today?", "Microsoft","Slogan")));
//        map.add(new MatchingMnemonic("WEHtpl", new MatchingMnemonicDetail("When EF Hutton talks, people listen", "EF Hutton","Slogan")));
//        map.add(new MatchingMnemonic("Wgatfy", new MatchingMnemonicDetail("We’ve got a taste for you", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("Whhsh", new MatchingMnemonicDetail("What happens here, stays here", "Las Vegas Convention and Visitors Authority","Slogan")));
//        map.add(new MatchingMnemonic("Wiaphtbto", new MatchingMnemonicDetail("When it absolutely, positively has to be there overnight", "Federal Express","Slogan")));
//        map.add(new MatchingMnemonic("Wiaphtbto", new MatchingMnemonicDetail("When it absolutely, positively has to be there overnight", "FedEx","Slogan")));
//        map.add(new MatchingMnemonic("Wirip", new MatchingMnemonicDetail("When it rains, it pours", "Morton Salt","Slogan")));
//        map.add(new MatchingMnemonic("Wiyw", new MatchingMnemonicDetail("What’s in your wallet?", "Capital One","Slogan")));
//        map.add(new MatchingMnemonic("Wkm", new MatchingMnemonicDetail("We know money", "AIG","Slogan")));
//        map.add(new MatchingMnemonic("Wlad", new MatchingMnemonicDetail("Works like a dream", "Ambien","Slogan")));
//        map.add(new MatchingMnemonic("Wlfafgm", new MatchingMnemonicDetail("We’re looking for a few good men", "U.S. Marines","Slogan")));
//        map.add(new MatchingMnemonic("Wltfais", new MatchingMnemonicDetail("We love to fly and it shows", "Delta Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Wltsys", new MatchingMnemonicDetail("We love to see you smile", "McDonald’s","Slogan")));
//        map.add(new MatchingMnemonic("Wmbd", new MatchingMnemonicDetail("We’re moving beyond documents", "Xerox","Slogan")));
//        map.add(new MatchingMnemonic("Wmc", new MatchingMnemonicDetail("We mean clean", "Bissell","Slogan")));
//        map.add(new MatchingMnemonic("WmtmtowWei", new MatchingMnemonicDetail("We make the money the old-fashioned way We earn it", "Smith Barney","Slogan")));
//        map.add(new MatchingMnemonic("Wmtw", new MatchingMnemonicDetail("We move the world", "DHL","Slogan")));
//        map.add(new MatchingMnemonic("Wnswfy", new MatchingMnemonicDetail("We never stop working for you", "Verizon Wireless","Slogan")));
//        map.add(new MatchingMnemonic("Wtb", new MatchingMnemonicDetail("Where’s the beef?", "Wendy’s","Slogan")));
//        map.add(new MatchingMnemonic("WtbtCotS", new MatchingMnemonicDetail("What’s the best tuna? Chicken of the Sea", "Chicken of the Sea","Slogan")));
//        map.add(new MatchingMnemonic("Wtcf", new MatchingMnemonicDetail("Where’s the cream filling?", "Hostess Cakes","Slogan")));
//        map.add(new MatchingMnemonic("Wtglacs", new MatchingMnemonicDetail("Winston tastes good like a cigarette should", "Winston","Slogan")));
//        map.add(new MatchingMnemonic("Wth", new MatchingMnemonicDetail("We try harder", "Avis","Slogan")));
//        map.add(new MatchingMnemonic("WthtT", new MatchingMnemonicDetail("Which twin has the Toni?", "Toni","Slogan")));
//        map.add(new MatchingMnemonic("Wtint", new MatchingMnemonicDetail(" When there is no tomorrow", "FedEx ","Slogan")));
//        map.add(new MatchingMnemonic("Wtmb", new MatchingMnemonicDetail("Where technology means business", "ZDNet","Slogan")));
//        map.add(new MatchingMnemonic("Wtoi", new MatchingMnemonicDetail("We turn on ideas", "Seagate","Slogan")));
//        map.add(new MatchingMnemonic("Wtpg", new MatchingMnemonicDetail("Where the pets go", "Petco","Slogan")));
//        map.add(new MatchingMnemonic("WtWTCH", new MatchingMnemonicDetail("What’s the Worst That Could Happen?", "Dr Pepper","Slogan")));
//        map.add(new MatchingMnemonic("Wuad", new MatchingMnemonicDetail("Wake up and drive", "Mitsubishi Motors","Slogan")));
//        map.add(new MatchingMnemonic("Wwsnwbit", new MatchingMnemonicDetail("We will sell no wine before its time", "Paul Masson","Slogan")));
//        map.add(new MatchingMnemonic("WwydfaKb", new MatchingMnemonicDetail("What would you do for a Klondike bar?", "Klondike Bar","Slogan")));
//        map.add(new MatchingMnemonic("Wybr", new MatchingMnemonicDetail("Will you be ready?", "Cialis","Slogan")));
//        map.add(new MatchingMnemonic("Wycetstvb", new MatchingMnemonicDetail("When you care enough to send the very best", "Hallmark","Slogan")));
//        map.add(new MatchingMnemonic("Wycfc", new MatchingMnemonicDetail("When you’re crazy for chicken", "El Pollo Loco","Slogan")));
//        map.add(new MatchingMnemonic("Wygifi", new MatchingMnemonicDetail("When you’ve got it, flaunt it", "Braniff Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Wygifi", new MatchingMnemonicDetail("When you got it, flaunt it", "Braniff Airlines","Slogan")));
//        map.add(new MatchingMnemonic("WyooSyoob", new MatchingMnemonicDetail("When you’re out of Schlitz, you’re out of beer", "Schlitz Beer","Slogan")));
//        map.add(new MatchingMnemonic("WysBysia", new MatchingMnemonicDetail("When you say Budweiser, you’ve said it all", "Budweiser","Slogan")));
//        map.add(new MatchingMnemonic("Yanftmatc", new MatchingMnemonicDetail("You are now free to move about the country", "Southwest Airlines","Slogan")));
//        map.add(new MatchingMnemonic("Ycalwb", new MatchingMnemonicDetail("You’ve come a long way, baby", "Virginia Slims Cigarettes","Slogan")));
//        map.add(new MatchingMnemonic("YcbsoS", new MatchingMnemonicDetail("You can be sure of Shell", "Shell Oil","Slogan")));
//        map.add(new MatchingMnemonic("Ycbtrt", new MatchingMnemonicDetail("You can’t beat the real thing", "Coca-Cola","Slogan")));
//        map.add(new MatchingMnemonic("YclalfadBu", new MatchingMnemonicDetail("You could learn a lot from a dummy Buckle up!", "National Highway Traffic Safety Administration","Slogan")));
//        map.add(new MatchingMnemonic("Yctycttmwwts", new MatchingMnemonicDetail("You can trust your car to the men who wear the star", "Texaco","Slogan")));
//        map.add(new MatchingMnemonic("Ydabt", new MatchingMnemonicDetail("You deserve a break today", "McDonald’s","Slogan")));
//        map.add(new MatchingMnemonic("YdhtbJtlL", new MatchingMnemonicDetail("You don’t have to be Jewish to love Levy’s", "Levy’s Rye Bread","Slogan")));
//        map.add(new MatchingMnemonic("Yff", new MatchingMnemonicDetail("Your flexible friend", "Access","Slogan")));
//        map.add(new MatchingMnemonic("Ygqwga", new MatchingMnemonicDetail("You’ve got questions, we’ve got answers", "Radio Shack","Slogan")));
//        map.add(new MatchingMnemonic("Ygu2mwgytw", new MatchingMnemonicDetail("You give us 22 minutes, we’ll give you the world", "Wins Radio, New York","Slogan")));
//        map.add(new MatchingMnemonic("YighwA", new MatchingMnemonicDetail("You’re in good hands with Allstate", "Allstate Insurance","Slogan")));
//        map.add(new MatchingMnemonic("YkwybT", new MatchingMnemonicDetail("You know when you’ve been Tango’d", "Tango","Slogan")));
//        map.add(new MatchingMnemonic("Yltwwf", new MatchingMnemonicDetail("You’ll love the way we fly", "Delta Airlines","Slogan")));
//        map.add(new MatchingMnemonic("YnfcuyZc", new MatchingMnemonicDetail("You’re not fully clean until you’re Zestfully clean", "Zest Soap","Slogan")));
//        map.add(new MatchingMnemonic("YOGaOWT", new MatchingMnemonicDetail("You Only Get an OO’ With Typhoo", "Typhoo","Slogan")));
//        map.add(new MatchingMnemonic("YpOp", new MatchingMnemonicDetail("Your potential Our passion", "Microsoft","Slogan")));
//        map.add(new MatchingMnemonic("YqTB", new MatchingMnemonicDetail("Yo quiero Taco Bell", "Taco Bell","Slogan")));
//        map.add(new MatchingMnemonic("YTnB", new MatchingMnemonicDetail("Yellow The new Brown", "DHL","Slogan")));
//        map.add(new MatchingMnemonic("YvOf", new MatchingMnemonicDetail("Your vision Our future", "Olympus ","Slogan")));
//        map.add(new MatchingMnemonic("YwwtywwybytwP", new MatchingMnemonicDetail("You’ll wonder where the yellow went when you brush your teeth with Pepsodent", "Pepsodent","Slogan")));
//        map.add(new MatchingMnemonic("ZZ", new MatchingMnemonicDetail("Zoom Zoom", "Mazda ","Slogan")));
//        map.add(new MatchingMnemonic("Zzz", new MatchingMnemonicDetail("Zoom, zoom, zoom", "Mazda","Slogan")));

    }
}
